---
- name: Run roles playbook
  hosts: all
  become: true
  become_method: sudo
  roles:
    - { role: wordpress-ubuntu, when: ansible_os_family == 'Debian' }
    - { role: create-user-groups, when: ansible_os_family == 'Debian' }
    - { role: wordpress-redhat, when: ansible_os_family == 'RedHat' }

...