---
# tasks file for wordpress
- name: Install prerequisites 
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - httpd
  - php-{{ php_version }}
  - php-mysql-{{ php_version }}
  - mariadb
  - mariadb-server
  notify: Start webserver

- name: Install MySQL
  package:
    name: 
      - mariadb
      - mariadb-server
    state: latest

- name: Start MySQL
  service:
    name: mariadb
    state: started
    enabled: yes
 
# Wordpress Installation
- name: Get wordpress 
  get_url:
    url: https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz
    dest: /tmp/wordpress-{{ wordpress_version }}.tar.gz
    mode: '0440'


- name: Unzip Wordpress
  unarchive:
    src: /tmp/wordpress-{{ wordpress_version }}.tar.gz
    dest: /var/www/html/
    remote_src: true

- name: Move wordpress
  shell: "cp -r  /var/www/html/wordpress/*   /var/www/html || exit 0"
  ignore_errors: true

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: testfile
    dest: /etc/testfile.conf
    mode: '0644'

- name: Fix file ownership
  file:
    path: /var/www/html
    owner: apache
    group: apache
    state: directory
    recurse: yes
 
- name: Restart httpd
  service:
    name: httpd
    state: restarted 