# handlers file for wordpress
- name: Start webserver
  when: 
  - ansible_facts['os_family'] == "Debian" 
  systemd: 
    name: "{{ item }}" 
    state: restarted
    enabled: true
  with_items:
  - apache2
  - telnet 

